version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  generate-and-publish-report:
    executor: python/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'pipb-{{ checksum "requirements.txt"  }}'
      - python/install-deps
      - save_cache:
          # Don't use python/(save|load)-cache because we need to cache bin as
          # well, jupyter uses it internally
          key: 'pipb-{{ checksum "requirements.txt"  }}'
          paths:
              - /home/circleci/.local/
      - run:
          command: jupyter nbconvert "Activity Report.ipynb" --to html --output /tmp/activity-report.html
          name: Generate HTML Report
      - store_artifacts:
          path: /tmp/activity-report.html

workflows:
  main:
    jobs:
      - generate-and-publish-report
