version: 2.1

orbs:
  python: circleci/python@0.2.1
  aws-cli: circleci/aws-cli@1.3.2

jobs:
  generate-report:
    executor: python/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'pip-v2-{{ checksum "requirements.txt"  }}'
      - python/install-deps
      - save_cache:
          # Don't use python/(save|load)-cache because we need to cache bin as
          # well, jupyter uses it internally
          key: 'pip-v2-{{ checksum "requirements.txt"  }}'
          paths:
              - /home/circleci/.local/
      - run:
          name: Generate HTML Report
          command: jupyter nbconvert "Activity Report.ipynb" --execute --to html --output /tmp/activity-report.html
      - persist_to_workspace:
          root: /tmp
          paths:
            - activity-report.html

  upload-to-s3:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: /tmp
      - aws-cli/setup
      - run:
          name: Generate S3 Key
          command: echo "activity/activity-report-$(date +'%Y-%m-%dT%H:%M:%S%z').html" > /tmp/key
      - run:
          name: Upload to S3
          command: aws s3 cp --storage-class INTELLIGENT_TIERING "/tmp/activity-report.html s3://janalytics-reports/$(cat /tmp/key)"


workflows:
  version: 2

  nightly:
    triggers:
      - schedule:
          cron: "0 23 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - generate-report
      - upload-to-s3:
          requires:
            - generate-report

  main:
    jobs:
      - generate-report
      - upload-to-s3:
          requires:
            - generate-report
